# Generated by Django 3.0.2 on 2020-01-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apuntes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=30)),
                ('materia', models.CharField(max_length=30)),
                ('docente', models.CharField(max_length=30)),
                ('apuntes', models.FileField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Parcial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=30)),
                ('semestre', models.CharField(max_length=30)),
                ('facultad', models.CharField(max_length=30)),
                ('materia', models.CharField(max_length=30)),
                ('docente', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=15)),
                ('imagen', models.FileField(upload_to='')),
                ('parcial', models.ImageField(upload_to='images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=30)),
                ('semestre', models.CharField(max_length=30)),
                ('facultad', models.CharField(max_length=30)),
                ('materia', models.CharField(max_length=30)),
                ('docente', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=15)),
                ('imagen', models.FileField(upload_to='')),
                ('taller', models.ImageField(upload_to='images/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
