# Generated by Django 3.0.2 on 2020-01-12 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20200112_0141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcial',
            old_name='parcial',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='taller',
            old_name='taller',
            new_name='imagen',
        ),
    ]
