# Generated by Django 3.0.2 on 2020-01-21 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20200112_0202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apuntes',
        ),
        migrations.DeleteModel(
            name='Taller',
        ),
        migrations.RemoveField(
            model_name='parcial',
            name='tipo',
        ),
    ]
