# Generated by Django 3.0.2 on 2020-01-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20200121_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcial',
            name='sede',
            field=models.CharField(default='Bogota', max_length=20),
        ),
    ]
